# Generated by Django 4.2.11 on 2024-06-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ItemImage',
            field=models.FileField(default=2, upload_to='uploads/Items'),
            preserve_default=False,
        ),
    ]
