# Generated by Django 4.2.11 on 2024-06-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_items_itemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('Id1', models.AutoField(primary_key=True, serialize=False)),
                ('column1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('Id2', models.AutoField(primary_key=True, serialize=False)),
                ('column2', models.CharField(max_length=50)),
                ('col1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.table1')),
            ],
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('Id3', models.AutoField(primary_key=True, serialize=False)),
                ('column3', models.CharField(max_length=50)),
                ('col2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.table2')),
            ],
        ),
    ]
