# Generated by Django 4.2.11 on 2024-06-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_table1_table2_table3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(max_length=50)),
                ('col2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tables2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(max_length=50)),
                ('col2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.tables1')),
            ],
        ),
        migrations.RemoveField(
            model_name='table2',
            name='col1',
        ),
        migrations.RemoveField(
            model_name='table3',
            name='col2',
        ),
        migrations.DeleteModel(
            name='Table1',
        ),
        migrations.DeleteModel(
            name='Table2',
        ),
        migrations.DeleteModel(
            name='Table3',
        ),
    ]
