# Generated by Django 4.2.11 on 2024-06-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_tables1_tables2_remove_table2_col1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tables1',
            new_name='Table1',
        ),
        migrations.RenameModel(
            old_name='Tables2',
            new_name='Table2',
        ),
    ]
