# Generated by Django 4.2.11 on 2024-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_rename_tables1_table1_rename_tables2_table2'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='Stutus',
            field=models.CharField(default='pendding'),
        ),
    ]
