# Generated by Django 4.2.11 on 2024-06-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_alter_orders_ordertime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='Stutus',
            new_name='Status',
        ),
    ]
