# Generated by Django 4.2.11 on 2024-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_rename_stutus_orderitems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='Status',
            field=models.CharField(default='pending'),
        ),
    ]
